### ISSUE TITLE
use_trajectory_lengths_cache error

### ISSUE THREAD

**Issue by euhruska** [markovmodel/PyEMMA#1077]
I have a script which loads in .dcd trajectories on one cluster, no problem. Then I copied these trajectories to a different cluster and the loading of these  .dcd trajectories with the exactly same script fails. Pyemma version 2.3.2, the dcd files are slightly larger (20G). The error said something about use_trajectory_lengths_cache, not sure what's wrong there, especially since it works on the first cluster.

```
data = coor.load(all_trajs, featurizer, stride=stride, chunk_size=100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eh22/anaconda2/lib/python2.7/site-packages/pyemma/coordinates/api.py", line 212, in load
    reader = create_file_reader(trajfiles, top, features, chunk_size=chunk_size if chunk_size is not None else 0, **kw)
  File "/home/eh22/anaconda2/lib/python2.7/site-packages/pyemma/coordinates/data/util/reader_utils.py", line 101, in create_file_reader
    chunksize=chunk_size)
  File "/home/eh22/anaconda2/lib/python2.7/site-packages/pyemma/coordinates/data/feature_reader.py", line 94, in __init__
    self.filenames = trajectories
  File "/home/eh22/anaconda2/lib/python2.7/site-packages/pyemma/coordinates/data/_base/datasource.py", line 115, in filenames
    if config.use_trajectory_lengths_cache:
  File "/home/eh22/anaconda2/lib/python2.7/site-packages/pyemma/util/config.py", line 356, in use_trajectory_lengths_cache
    return self._conf_values.getboolean('pyemma', 'use_trajectory_lengths_cache')
  File "/home/eh22/anaconda2/lib/python2.7/ConfigParser.py", line 370, in getboolean
    raise ValueError, 'Not a boolean: %s' % v
ValueError: Not a boolean: Truee
```

**Comment by marscher** [comment]
solved, was a tiny config file mistake.
