### ISSUE TITLE
_progress_register error

### ISSUE THREAD

**Issue by euhruska** [markovmodel/PyEMMA#1201]
I got an error with a _progress_register. When I try to rerun this command is sometimes works, but usually, repeats the error below. 
Pyemma version 2.4 conda-forge, python 3.6.2 using gpu
Should I do _progress_register(amount_of_work, stage=1) in my script?

```
cl = coor.cluster_kmeans(data=Y)
12-12-17 15:29:02 pyemma.coordinates.clustering.kmeans.KmeansClustering[7] INFO     The number of cluster centers was not specified, using min(sqrt(N), 5000)=321 as n_clusters.
                                                                                12-12-17 15:29:10 pyemma.coordinates.clustering.kmeans.KmeansClustering[7] INFO     Cluster centers converged after 8 steps.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "x/lib/python3.6/site-packages/pyemma/coordinates/api.py", line 1470, in cluster_kmeans
    return _param_stage(data, res, stride=stride, chunk_size=chunk_size)
  File "x/lib/python3.6/site-packages/pyemma/coordinates/api.py", line 847, in _param_stage
    this_stage.estimate(X=input_stage, stride=stride)21 [00:03<00:00, 97.66it/s]
  File "x/lib/python3.6/site-packages/pyemma/coordinates/data/_base/transformer.py", line 219, in estimate
    super(StreamingEstimationTransformer, self).estimate(X, **kwargs) 97.66it/s]
  File "x/lib/python3.6/site-packages/pyemma/coordinates/data/_base/streaming_estimator.py", line 51, in estimate
    super(StreamingEstimator, self).estimate(X, **kwargs)
  File "x/lib/python3.6/site-packages/pyemma/_base/estimator.py", line 369, in estimate
    self._model = self._estimate(X)
  File "x/lib/python3.6/site-packages/pyemma/coordinates/clustering/kmeans.py", line 214, in _estimate
    self._finish_estimate()
  File "x/lib/python3.6/site-packages/pyemma/coordinates/clustering/kmeans.py", line 230, in _finish_estimate
    self._progress_force_finish(1)
  File "x/lib/python3.6/site-packages/progress_reporter/reporter.py", line 220, in _progress_force_finish
    pg = self.__check_stage_registered(stage)
  File "x/lib/python3.6/site-packages/progress_reporter/reporter.py", line 106, in __check_stage_registered
    raise RuntimeError('call _progress_register(amount_of_work, stage={}) on this instance first!'.format(stage))
RuntimeError: call _progress_register(amount_of_work, stage=1) on this instance first!
```

**Comment by euhruska** [comment]
Once I restarted the job the error is gone, but returns quickly (within 10 times running clustering).

**Comment by marscher** [comment]
You are not supposed to call this private method yourself. Which version 
of progress_reporter do you have? There was an update recently.

**Comment by euhruska** [comment]
Got progress_reporter version 1.4. I didn't call it, it just appeared in the error message.

**Comment by marscher** [comment]
On 13.12.2017 18:31, Eugen Hruska wrote:
> Reopened #1201.
> 

I see whats going on there. Will provide a fix soon.

**Comment by marscher** [comment]
does downgrading progress_reporter to 1.3.1 solve the problem?

**Comment by marscher** [comment]
it does. So this affects only new installations since 1.4 release of progress_reporter (this rel has only been tested with devel version of pyemma). I will pin the version on conda-forge, but there are currently some version conflicts with mdtraj, which needs to be resolved first.

Thanks for reporting this!

**Comment by marscher** [comment]
https://github.com/conda-forge/pyemma-feedstock/pull/10

**Comment by marscher** [comment]
merged.
