### ISSUE TITLE
Error unpickling MaximumLikelihoodMSM object from version 2.4 in version 2.5.1

### ISSUE THREAD

**Issue by cescgina** [markovmodel/PyEMMA#1279]
Hello,

I am trying to load a MaximumLikelihoodMSM object using pickle. The object was created using version 2.4, but after upgrading to version 2.5.1 and trying to load I get the following error:
```python
21-03-18 15:54:26 pyemma._base.serialization.serialization ERROR    exception during unpickling 1.0 step
Traceback (most recent call last):
  File "/home/jgilaber/.local/lib/python2.7/site-packages/pyemma/_base/serialization/serialization.py", line 419, in __setstate__
    state.pop('class_tree_versions')
KeyError: 'class_tree_versions'
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    msm = pickle.load(f)
  File "/usr/lib64/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib64/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib64/python2.7/pickle.py", line 1223, in load_build
    setstate(state)
  File "/home/jgilaber/.local/lib/python2.7/site-packages/pyemma/_base/serialization/serialization.py", line 419, in __setstate__
    state.pop('class_tree_versions')
KeyError: 'class_tree_versions'
```
I am using pyemma 2.5.1 with openSUSE Tumbleweed 42.3, the environment information can be found in the following text file (outupt of pip list)
[pip_list.txt](https://github.com/markovmodel/PyEMMA/files/1833795/pip_list.txt)

The error can be reproduced by running:
```python
import pickle

with open("MSM_object_0.pkl") as f:
    msm = pickle.load(f)
```
with the attached zipped pickle object
[MSM_object_0.pkl.zip](https://github.com/markovmodel/PyEMMA/files/1833784/MSM_object_0.pkl.zip)

**Comment by marscher** [comment]
The recent version is clever about the serialization state. I think this one should be easy to fix. Can you apply the following patch and see if it works please?
[set_state.patch.txt](https://github.com/markovmodel/PyEMMA/files/1833864/set_state.patch.txt)

**Comment by cescgina** [comment]
I don't get the error with this change, however the object appears to be empty. For example doing
```python
print msm.stationary_distribution
```
gives None and when calling methods such as timescales, eigenvectors_right or eigenvalues I get the following error
```python
Found exception:  index 0 is out of bounds for axis 0 with size 0
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-17-8163db069891> in <module>()
----> 1 msm.eigenvalues()

/home/jgilaber/.local/lib/python2.7/site-packages/pyemma/msm/models/msm.pyc in eigenvalues(self, k)
    375 
    376         """
--> 377         self._ensure_eigenvalues(neig=k)
    378         return self._eigenvalues[:k]
    379 

/home/jgilaber/.local/lib/python2.7/site-packages/pyemma/msm/models/msm.pyc in _ensure_eigenvalues(self, neig)
    314         except AttributeError:
    315             # no eigendecomposition yet - compute:
--> 316             self._compute_eigenvalues(neig)
    317 
    318     def _compute_eigendecomposition(self, neig):

/home/jgilaber/.local/lib/python2.7/site-packages/pyemma/msm/models/msm.pyc in _compute_eigenvalues(self, neig)
    297                                        reversible=True, mu=self.stationary_distribution)
    298         else:
--> 299             self._eigenvalues = anaeig(self.transition_matrix, k=neig, ncv=self.ncv, reversible=False)
    300 
    301         if _np.all(self._eigenvalues.imag == 0):

/home/jgilaber/.local/lib/python2.7/site-packages/msmtools/analysis/api.pyc in eigenvalues(T, k, ncv, reversible, mu)
    401 
    402     """
--> 403     T = _types.ensure_ndarray_or_sparse(T, ndim=2, uniform=True, kind='numeric')
    404     if _issparse(T):
    405         return sparse.decomposition.eigenvalues(T, k, ncv=ncv, reversible=reversible, mu=mu)

/home/jgilaber/.local/lib/python2.7/site-packages/msmtools/util/types.pyc in ensure_ndarray_or_sparse(A, shape, uniform, ndim, size, dtype, kind)
    425         except:
    426             raise AssertionError('Given argument cannot be converted to an ndarray:\n'+str(A))
--> 427     assert_array(A, shape=shape, uniform=uniform, ndim=ndim, size=size, dtype=dtype, kind=kind)
    428     return A
    429 

/home/jgilaber/.local/lib/python2.7/site-packages/msmtools/util/types.pyc in assert_array(A, shape, uniform, ndim, size, dtype, kind)
    392             print('Found exception: ',ex)
    393             raise AssertionError('Given argument is not an array of the expected shape or type:\n'+
--> 394                                  'arg = '+str(A)+'\ntype = '+str(type(A)))
    395 
    396 def ensure_ndarray(A, shape=None, uniform=None, ndim=None, size=None, dtype=None, kind=None):

AssertionError: Given argument is not an array of the expected shape or type:
arg = None
type = <type 'numpy.ndarray'>
```

**Comment by marscher** [comment]
What leads to the assumption that this operation is even supported? Un-pickling in future version will work until we change the code. The new pickle interface now takes care, we can provide future compatibility, but never backwards.
I can change the code to path through old serializations, and print and big fat warning that things might fail silently and we can not give support for that.

**Comment by cescgina** [comment]
Ok, I will simply downgrade then.
Thanks!

**Comment by marscher** [comment]
I will add a patch, so you can load your old data in the new version, but one has to keep in mind that this is most likely error prone.
