### ISSUE TITLE
MemoryError when computing TICA with high stride arguments

### ISSUE THREAD

**Issue by euhruska** [markovmodel/PyEMMA#1305]
I get a memory error, with featurizer.dimension() 3003, I'm not sure why this happens. It happens quite fast, after about 10s. 
```
tica_obj = coor.tica(inp, lag=lag, commute_map=True, kinetic_map=False, var_cutoff=0.8, stride=stride_tica)>>>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch1/eh22/conda/envs/py3/lib/python3.6/site-packages/pyemma/coordinates/api.py", line 1261, in tica
    res.estimate(data, chunksize=cs)
  File "/scratch1/eh22/conda/envs/py3/lib/python3.6/site-packages/pyemma/coordinates/transform/tica.py", line 159, in estimate
    return super(TICA, self).estimate(X, **kwargs)
  File "/scratch1/eh22/conda/envs/py3/lib/python3.6/site-packages/pyemma/coordinates/data/_base/transformer.py", line 212, in estimate
    super(StreamingEstimationTransformer, self).estimate(X, **kwargs)
  File "/scratch1/eh22/conda/envs/py3/lib/python3.6/site-packages/pyemma/coordinates/data/_base/streaming_estimator.py", line 45, in estimate
    super(StreamingEstimator, self).estimate(X, **kwargs)
  File "/scratch1/eh22/conda/envs/py3/lib/python3.6/site-packages/pyemma/_base/estimator.py", line 412, in estimate
    self._model = self._estimate(X)
  File "/scratch1/eh22/conda/envs/py3/lib/python3.6/site-packages/pyemma/coordinates/transform/tica.py", line 206, in _estimate
    covar.estimate(iterable, chunksize=self.chunksize, **kw)
  File "/scratch1/eh22/conda/envs/py3/lib/python3.6/site-packages/pyemma/coordinates/data/_base/streaming_estimator.py", line 45, in estimate
    super(StreamingEstimator, self).estimate(X, **kwargs)
  File "/scratch1/eh22/conda/envs/py3/lib/python3.6/site-packages/pyemma/_base/estimator.py", line 412, in estimate
    self._model = self._estimate(X)
  File "/scratch1/eh22/conda/envs/py3/lib/python3.6/site-packages/pyemma/coordinates/estimation/covariance.py", line 214, in _estimate
    for data, weight in zip(it, it_weights):
  File "/scratch1/eh22/conda/envs/py3/lib/python3.6/site-packages/pyemma/coordinates/data/_base/iterable.py", line 226, in __next__
    return self.next()
  File "/scratch1/eh22/conda/envs/py3/lib/python3.6/site-packages/pyemma/coordinates/data/_base/iterable.py", line 246, in next
    itraj, data_lagged = self._it.next()
  File "/scratch1/eh22/conda/envs/py3/lib/python3.6/site-packages/pyemma/coordinates/data/_base/datasource.py", line 1005, in next
    X = self._it_next()
  File "/scratch1/eh22/conda/envs/py3/lib/python3.6/site-packages/pyemma/coordinates/data/_base/datasource.py", line 985, in _it_next
    X = self._use_cols(self._next_chunk())
  File "/scratch1/eh22/conda/envs/py3/lib/python3.6/site-packages/pyemma/coordinates/data/feature_reader.py", line 396, in _next_chunk
    res = self._data_source.featurizer.transform(chunk)
  File "/scratch1/eh22/conda/envs/py3/lib/python3.6/site-packages/pyemma/coordinates/data/featurization/featurizer.py", line 915, in transform
    vec = f.transform(traj).astype(np.float32)
  File "/scratch1/eh22/conda/envs/py3/lib/python3.6/site-packages/pyemma/coordinates/data/featurization/distances.py", line 107, in transform
    D = mdtraj.compute_contacts(traj, contacts=self.contacts, scheme=self.scheme, periodic=self.periodic)[0]
  File "/scratch1/eh22/conda/envs/py3/lib/python3.6/site-packages/mdtraj/geometry/contact.py", line 208, in compute_contacts
    atom_distances = md.compute_distances(traj, atom_pairs, periodic=periodic)
  File "/scratch1/eh22/conda/envs/py3/lib/python3.6/site-packages/mdtraj/geometry/distance.py", line 81, in compute_distances
    out = np.empty((xyz.shape[0], pairs.shape[0]), dtype=np.float32)
MemoryError
```
python 3.6.3, pyemma 2.5.2
[version.txt](https://github.com/markovmodel/PyEMMA/files/2032763/version.txt)

**Comment by marscher** [comment]
did you specify chunksize? Whats the lag time?

**Comment by euhruska** [comment]
chunksize=5000
lag=10

**Comment by franknoe** [comment]
This is very weird. The dimension and chunksize are too small to cause a memoryerror. Since it happens after 10 seconds this sounds like there is a memory leak. However there is no C-code on our side at this stage.

**Comment by euhruska** [comment]
the error is repeatable. Is there a way to check for memory leaks or what happens there?

**Comment by marscher** [comment]
Frank is right about the memory leak suspicion, but it could also be our code - because running covariances uses an extension as well. Eugen you can run through valgrind, like this:

`valgrind --leak-check=full  -- python script.py`

This will produce a very verbose output at stdout, which should be investigated for the pattern "definitely lost". If you spot these have a closer look at the stack (c file names and lines, which indicates the location of the memory leak).

**Comment by marscher** [comment]
for tica itself I can not spot anything like a mem leak.

**Comment by euhruska** [comment]
there are some definitely lost: 156,610 bytes in 83 blocks
[valgrindout.txt](https://github.com/markovmodel/PyEMMA/files/2033171/valgrindout.txt)

**Comment by marscher** [comment]
152KiB is not that much to exceed memory. Can you allocate some large numpy arrays (filled with data), eg numpy.random.random to check whether you are hitting some memory constraints of the system?

**Comment by euhruska** [comment]
not sure it changed anything, but added np.random.rand(1000000) before
[valgrindout2.txt](https://github.com/markovmodel/PyEMMA/files/2036370/valgrindout2.txt)

**Comment by marscher** [comment]
What is the memory limit of the system? I do not think it has anything
to do with our code. Usually a memory request (malloc etc.) would also
use swap space before Python throws a MemoryError.

**Comment by euhruska** [comment]
64G, shows 50G free. I don't see how it can use up that much memory within seconds.

**Comment by marscher** [comment]
On 24.05.2018 20:17, Eugen Hruska wrote:
> 64G, shows 50G free. I don't see how it can use up that much memory within seconds.
> 
could you attach a debugger like pdb and get the shape of the array that
is being created, when the memory error is raised?

eg run your script in ipython, after the crash run the magic command
%debug and print in the variable names for the shape of the array. I
guess there are far too large.

**Comment by euhruska** [comment]
which variable? I get test1.shape as expected

**Comment by marscher** [comment]
On 24.05.2018 21:11, Eugen Hruska wrote:
> which variable? I get test1.shape as expected
> 

    out = np.empty((xyz.shape[0], pairs.shape[0]), dtype=np.float32)

This fails, so the desired shape is too large, so it would be of
interest what the actual shape is like.

**Comment by euhruska** [comment]
just checked on another cluster, issue repeats itself

**Comment by marscher** [comment]
which trajectory format are you using? Can you share the script leading to the error?

**Comment by euhruska** [comment]
loading pdb topology and dcd trajectory

**Comment by fabian-paul** [comment]
You could try to run with a memory profiler (https://pypi.org/project/memory_profiler/)?
A couple of times I made stupid mistakes with numpy broadcasting which resulted in the creation of huge intermediate arrays. Maybe the same problem here? Such mistakes are hard to find without a profiler.

**Comment by marscher** [comment]
The allocation which fails has the shape:
ipdb> xyz.shape[0], pairs.shape[0]
(223470, 179120)

which is absolutely too large. What is really suprising me, is that the FeatureReaderIterator has a chunksize of [FeatureReaderIterator chunk=22347, stride=1, skip=0]. So it should not yield such a big chunk at all.

**Comment by fabian-paul** [comment]
223470 = lag*22347 ?

**Comment by euhruska** [comment]
yes, lag=10

**Comment by marscher** [comment]
factor ten is negligible in this case. The automatic chunksize computation fails for this case.

**Comment by marscher** [comment]
The io efficient iterator multiplies the chunksize with the readers stride, therefore we end up in this scenario. Maybe there is another way of handling the stride? @clonker

**Comment by clonker** [comment]
If we want to keep this style of optimization the only thing that comes to mind right now is to use the `GCD(stride, lag+stride)` as stride for the internal iterator instead of just `stride=1`.
But if we are unlucky this again evaluates to `1` and we have the same problem.

We could calculate the memory it would take to store the internal chunk, i.e.,
```
chunksize * GCD(stride, lag+stride) * ndim * sizeof(dtype)
```
and have a cutoff in the configuration file when to use the io optimized iterator and when to fall back to the one that does two io operations.

**Comment by marscher** [comment]
On 05/31/2018 11:10 AM, Moritz Hoffmann wrote:
> If we want to keep this style of optimization the only thing that comes
> to mind right now is to use the |GCD(stride, lag+stride)| as stride for
> the internal iterator instead of just |stride=1|.
> But if we are unlucky this again evaluates to |1| and we have the same
> problem.
> 
> We could calculate the memory it would take to store the internal chunk,
> i.e.,
> 
> |chunksize * GCD(stride, lag+stride) * ndim * sizeof(dtype) |
> 
> and have a cutoff in the configuration file when to use the io optimized
> iterator and when to fall back to the one that does two io operations.

Thanks for your feedback, I'd prefer the fallback solution, because it
is fail safe.
