### ISSUE TITLE
msm.its element is ambiguous

### ISSUE THREAD

**Issue by euhruska** [markovmodel/PyEMMA#1309]
I ran pyemma.msm.its on couple trajectories, but get on pyemma 2.5 python 2.7.3: 
```
 its = pyemma.msm.its(dtrajs,msm_lagtimes)
estimating MaximumLikelihoodMSM:  75%|███████████████████████████████████████████████████████▌                  | 9/12 [01:14<00:27,  9.11s/it]
30-05-18 20:48:17 pyemma.msm.estimators.maximum_likelihood_msm.MaximumLikelihoodMSM[1] WARNING  Ignored error during estimation: Stationary dis
tribution contains entries smaller than 1e-15 during iteration
estimating MaximumLikelihoodMSM:  83%|████████████████████████████████████████████████████████████▊            | 10/12 [01:16<00:13,  6.89s/it]
30-05-18 20:48:18 pyemma.msm.estimators.maximum_likelihood_msm.MaximumLikelihoodMSM[2] WARNING  Ignored error during estimation: Stationary dis
tribution contains entries smaller than 1e-15 during iteration
estimating MaximumLikelihoodMSM:  92%|██████████████████████████████████████████████████████████████████▉      | 11/12 [01:17<00:05,  5.11s/it]
30-05-18 20:48:18 pyemma.msm.estimators.maximum_likelihood_msm.MaximumLikelihoodMSM[3] WARNING  Ignored error during estimation: Stationary dis
tribution contains entries smaller than 1e-15 during iteration
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [01:18<00:00,  3.81s/it]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch1/eh22/conda/envs/extasy2/lib/python2.7/site-packages/pyemma/msm/api.py", line 228, in timescales_msm
    itsobj.estimate(dtrajs)
  File "/scratch1/eh22/conda/envs/extasy2/lib/python2.7/site-packages/pyemma/msm/estimators/implied_timescales.py", line 148, in estimate
    return super(ImpliedTimescales, self).estimate(X, **params)
  File "/scratch1/eh22/conda/envs/extasy2/lib/python2.7/site-packages/pyemma/_base/estimator.py", line 412, in estimate
    self._model = self._estimate(X)
  File "/scratch1/eh22/conda/envs/extasy2/lib/python2.7/site-packages/pyemma/msm/estimators/implied_timescales.py", line 204, in _estimate
    self._postprocess_results(models)
  File "/scratch1/eh22/conda/envs/extasy2/lib/python2.7/site-packages/pyemma/msm/estimators/implied_timescales.py", line 222, in _postprocess_results
    if bad:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

When running on python 3.6.3 and pyemma 2.7.2 it changes to
```
30-05-18 21:25:32 pyemma.msm.estimators.implied_timescales.ImpliedTimescales[4] WARNING  Estimation has failed at lagtimes: [ 500  750 1000]. Details:
['Error at lag time 500: Stationary distribution contains entries smaller than '
 '1e-15 during iteration',
 'Error at lag time 750: Stationary distribution contains entries smaller than '
 '1e-15 during iteration',
 'Error at lag time 1000: Stationary distribution contains entries smaller '
 'than 1e-15 during iteration']
30-05-18 21:25:32 pyemma.msm.estimators.implied_timescales.ImpliedTimescales[4] WARNING  Some timescales could not be computed. Timescales array is smaller than expected or contains NaNs

```
It leads to couple Nan values for longer timescales.
What causes this, is the msm disconnected? Is there a way to figure out which states are disconnected?

**Comment by marscher** [comment]
I do not get your concern here. What do you think is ambiguous?

**Comment by euhruska** [comment]
Maybe not ambiguous, but is it correct that this is caused  by disconnected msm? Is there a way to figure out which states are disconnected?
