### ISSUE TITLE
ImportError: No module named 'bar'

### ISSUE THREAD

**Issue by euhruska** [markovmodel/PyEMMA#1357]
import error
```
Traceback (most recent call last):
  File "script.py", line 7, in <module>
    import pyemma
  File "/mnt/b/projects/sciteam/bamm/hruska/vpy6/lib/python3.5/site-packages/pyemma/__init__.py", line 36, in <module>
    from . import plots
  File "/mnt/b/projects/sciteam/bamm/hruska/vpy6/lib/python3.5/site-packages/pyemma/plots/__init__.py", line 77, in <module>
    from .thermoplots import *
  File "/mnt/b/projects/sciteam/bamm/hruska/vpy6/lib/python3.5/site-packages/pyemma/plots/thermoplots.py", line 19, in <module>
    from pyemma.thermo import WHAM as _WHAM
  File "/mnt/b/projects/sciteam/bamm/hruska/vpy6/lib/python3.5/site-packages/pyemma/thermo/__init__.py", line 54, in <module>
    from pyemma.thermo.models import StationaryModel, MultiThermModel, MEMM
  File "/mnt/b/projects/sciteam/bamm/hruska/vpy6/lib/python3.5/site-packages/pyemma/thermo/models/__init__.py", line 18, in <module>
    from .stationary import StationaryModel
  File "/mnt/b/projects/sciteam/bamm/hruska/vpy6/lib/python3.5/site-packages/pyemma/thermo/models/stationary.py", line 28, in <module>
    from thermotools.util import logsumexp as _logsumexp
  File "/mnt/b/projects/sciteam/bamm/hruska/vpy6/lib/python3.5/site-packages/thermotools/__init__.py", line 30, in <module>
    from . import cset
  File "/mnt/b/projects/sciteam/bamm/hruska/vpy6/lib/python3.5/site-packages/thermotools/cset.py", line 31, in <module>
    import bar as _bar
ImportError: No module named 'bar'
```

pyemma 2.5.4, thermotools 0.2.6, python 3.5.5
installed with ```pip install pyemma```

**Comment by marscher** [comment]
On 9/4/18 10:38 PM, Eugen Hruska wrote:
> import error
> ```
> Traceback (most recent call last):
>   File "script.py", line 7, in <module>
>     import pyemma
>   File "/mnt/b/projects/sciteam/bamm/hruska/vpy6/lib/python3.5/site-packages/pyemma/__init__.py", line 36, in <module>
>     from . import plots
>   File "/mnt/b/projects/sciteam/bamm/hruska/vpy6/lib/python3.5/site-packages/pyemma/plots/__init__.py", line 77, in <module>
>     from .thermoplots import *
>   File "/mnt/b/projects/sciteam/bamm/hruska/vpy6/lib/python3.5/site-packages/pyemma/plots/thermoplots.py", line 19, in <module>
>     from pyemma.thermo import WHAM as _WHAM
>   File "/mnt/b/projects/sciteam/bamm/hruska/vpy6/lib/python3.5/site-packages/pyemma/thermo/__init__.py", line 54, in <module>
>     from pyemma.thermo.models import StationaryModel, MultiThermModel, MEMM
>   File "/mnt/b/projects/sciteam/bamm/hruska/vpy6/lib/python3.5/site-packages/pyemma/thermo/models/__init__.py", line 18, in <module>
>     from .stationary import StationaryModel
>   File "/mnt/b/projects/sciteam/bamm/hruska/vpy6/lib/python3.5/site-packages/pyemma/thermo/models/stationary.py", line 28, in <module>
>     from thermotools.util import logsumexp as _logsumexp
>   File "/mnt/b/projects/sciteam/bamm/hruska/vpy6/lib/python3.5/site-packages/thermotools/__init__.py", line 30, in <module>
>     from . import cset
>   File "/mnt/b/projects/sciteam/bamm/hruska/vpy6/lib/python3.5/site-packages/thermotools/cset.py", line 31, in <module>
>     import bar as _bar
> ImportError: No module named 'bar'
> ```
> 
> pyemma 2.5.4, thermotools 0.2.6, python 3.5.5
> installed with ```pip install pyemma```
> 

that is a bug in thermotools. It does not use absolute imports for
Python3. It seems like only the conda-forge version is patched...

**Comment by marscher** [comment]
will be fixed by pypi release 0.2.7 of thermotools.

**Comment by marscher** [comment]
@euhruska you can install the pip version right now via:

pip install git+https://github.com/markovmodel/thermotools@0.2.7

**Comment by euhruska** [comment]
thermotools@0.2.7 works, thanks
