### ISSUE TITLE
Bayesian Hidden Markov model got an unexpected keyword argument 'desc'

### ISSUE THREAD

**Issue by WenHuiShen-Bio** [markovmodel/PyEMMA#1604]
When I want to analyze Hidden Markov Network, I have the following problem

`hmm=pyemma.msm.bayesian_hidden_markov_model(dtrajs,5, lag=30,stride=10, mincount_connectivity=0.2)`

> Sampling HMSMs:   0%|          | 0/100 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/xhshi/whshen/vscode/FDM-openmm-MSM/1PGB/rmsd3.0/pyemma/hmm.py", line 42, in <module>
    hmm=pyemma.msm.bayesian_hidden_markov_model(dtrajs,5, lag=30,stride=10, mincount_connectivity=0.02)
  File "/home/xhshi/whshen/anaconda3/envs/workshop/lib/python3.9/site-packages/pyemma/msm/api.py", line 1375, in bayesian_hidden_markov_model
    return bhmsm_estimator.estimate(dtrajs)
  File "/home/xhshi/whshen/anaconda3/envs/workshop/lib/python3.9/site-packages/pyemma/_base/estimator.py", line 418, in estimate
    self._model = self._estimate(X)
  File "/home/xhshi/whshen/anaconda3/envs/workshop/lib/python3.9/site-packages/pyemma/msm/estimators/bayesian_hmsm.py", line 313, in _estimate
    estimator.fit(dtrajs, n_burn_in=0, n_thin=1, progress=progress)
  File "/home/xhshi/whshen/anaconda3/envs/workshop/lib/python3.9/site-packages/deeptime/base.py", line 417, in __call__
    return self.fit_method(*args, **kwargs)
  File "/home/xhshi/whshen/anaconda3/envs/workshop/lib/python3.9/site-packages/deeptime/markov/hmm/_bayesian_hmm.py", line 610, in fit
    for _ in progress(range(self.n_samples), desc="Drawing samples", leave=False):
TypeError: __init__() got an unexpected keyword argument 'desc'
Sampling HMSMs:   0%|          | 0/100 [11:47<?, ?it/s]

How can I solve this problem, thanks.

**Comment by D16ERG** [comment]
I encountered the same issue. Although this issue was also later mentioned in #1610 ; it has not been resolved AFAIK.
