### ISSUE TITLE
Error when doing a setup.py develop on dev_release_1.3 branch

### ISSUE THREAD

**Issue by ppxasjsm** [markovmodel/PyEMMA#471]
This is the error I get...

```
python setup.py develop
setup.py:255: UserWarning: using git, require cython
  warnings.warn('using git, require cython')
running develop
creating /tmp/hasfunction-QhMdJc/tmp
creating /tmp/hasfunction-QhMdJc/tmp/hasfunction-QhMdJc
cc -c /tmp/hasfunction-QhMdJc/funcname.c -o /tmp/hasfunction-QhMdJc/tmp/hasfunction-QhMdJc/funcname.o
cc /tmp/hasfunction-QhMdJc/tmp/hasfunction-QhMdJc/funcname.o -o /tmp/hasfunction-QhMdJc/a.out
creating /tmp/hasfunction-6AnH8T/tmp
creating /tmp/hasfunction-6AnH8T/tmp/hasfunction-6AnH8T
cc -c /tmp/hasfunction-6AnH8T/funcname.c -o /tmp/hasfunction-6AnH8T/tmp/hasfunction-6AnH8T/funcname.o
cc /tmp/hasfunction-6AnH8T/tmp/hasfunction-6AnH8T/funcname.o -lgomp -o /tmp/hasfunction-6AnH8T/a.out
setup.py:143: UserWarning: enabled openmp
  warnings.warn('enabled openmp')
running egg_info
writing requirements to pyEMMA.egg-info/requires.txt
writing pyEMMA.egg-info/PKG-INFO
writing top-level names to pyEMMA.egg-info/top_level.txt
writing dependency_links to pyEMMA.egg-info/dependency_links.txt
package init file 'pyemma-ipython/__init__.py' not found (or not a regular file)
reading manifest file 'pyEMMA.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'testfiles/*' under directory 'pyemma'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.orig' found anywhere in distribution
no previously-included directories found matching 'doc/build'
no previously-included directories found matching 'doc/source/generated'
no previously-included directories found matching 'doc/source/api/generated'
warning: no directories found matching 'pyemma-ipython'
warning: no previously-included files matching '.ipynb_checkpoints' found under directory 'pyemma-ipython'
warning: no previously-included files matching 'git' found under directory '*'
warning: no files found matching 'pyemma/msm/estimation/dense/*.h'
warning: no files found matching 'pyemma/msm/estimation/sparse/*.h'
warning: no files found matching 'pyemma/msm/estimation/dense/mle_trev_given_pi.c'
warning: no files found matching 'pyemma/msm/estimation/sparse/mle_trev_given_pi.c'
warning: no files found matching '*.pyx' under directory 'pyemma'
no previously-included directories found matching '.eggs'
writing manifest file 'pyEMMA.egg-info/SOURCES.txt'
running build_ext
Creating /home/ppxasjsm/anaconda/lib/python2.7/site-packages/pyEMMA.egg-link (link to .)
pyEMMA 1.2.1+229.gd4e67f5 is already the active version in easy-install.pth

Installed /home/ppxasjsm/Projects/pyEMMA/PyEMMA
Processing dependencies for pyEMMA==1.2.1+229.gd4e67f5
Searching for bhmm
Reading https://pypi.python.org/simple/bhmm/
Best match: bhmm 0.3.0
Downloading https://pypi.python.org/packages/source/b/bhmm/bhmm-0.3.0.tar.gz#md5=6fe276a1edc5732e44baf037b50e05de
Processing bhmm-0.3.0.tar.gz
Writing /tmp/easy_install-PI7_6a/bhmm-0.3.0/setup.cfg
Running bhmm-0.3.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-PI7_6a/bhmm-0.3.0/egg-dist-tmp-hRE0pR
Traceback (most recent call last):
  File "setup.py", line 270, in <module>
    setup(**metadata)
  File "/home/ppxasjsm/anaconda/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/ppxasjsm/anaconda/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/ppxasjsm/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/ppxasjsm/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/command/develop.py", line 32, in run
  File "/home/ppxasjsm/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/command/develop.py", line 132, in install_for_development
  File "/home/ppxasjsm/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/command/easy_install.py", line 709, in process_distribution
  File "/home/ppxasjsm/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 836, in resolve

  File "/home/ppxasjsm/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 1081, in best_match

  File "/home/ppxasjsm/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 1093, in obtain

  File "/home/ppxasjsm/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/command/easy_install.py", line 629, in easy_install
  File "/home/ppxasjsm/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/command/easy_install.py", line 659, in install_item
  File "/home/ppxasjsm/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/command/easy_install.py", line 842, in install_eggs
  File "/home/ppxasjsm/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/command/easy_install.py", line 1070, in build_and_install
  File "/home/ppxasjsm/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/command/easy_install.py", line 1056, in run_setup
  File "/home/ppxasjsm/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/sandbox.py", line 240, in run_setup
  File "/home/ppxasjsm/anaconda/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ppxasjsm/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/sandbox.py", line 193, in setup_context
  File "/home/ppxasjsm/anaconda/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ppxasjsm/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/sandbox.py", line 164, in save_modules
  File "/home/ppxasjsm/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/sandbox.py", line 139, in resume
  File "/home/ppxasjsm/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/sandbox.py", line 152, in save_modules
  File "/home/ppxasjsm/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/sandbox.py", line 193, in setup_context
  File "/home/ppxasjsm/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/sandbox.py", line 237, in run_setup
  File "/home/ppxasjsm/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/sandbox.py", line 267, in run
  File "/home/ppxasjsm/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/sandbox.py", line 236, in runner
  File "/home/ppxasjsm/anaconda/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/sandbox.py", line 46, in _execfile
  File "/tmp/easy_install-PI7_6a/bhmm-0.3.0/setup.py", line 173, in <module>
    # this may happen, if numpy requirement is already fulfilled.
  File "/home/ppxasjsm/anaconda/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 754, in cythonize
    aliases=aliases)
  File "/home/ppxasjsm/anaconda/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 647, in create_extension_list
    raise TypeError(pattern)
TypeError: <setuptools.extension.Extension instance at 0x7ff6303966c8>
```

**Comment by clonker** [comment]
It looks like your bhmm version is out of date, should be 0.4.2.

**Comment by marscher** [comment]
I think 0.4.2 is not on pypi, since bhmm people are not releasing 
systematically everything but only the stuff individuals need (conda 
packages). This is very bad practice and should be avoided/fixed.

Please install bhmm with conda, then it will work.

**Comment by franknoe** [comment]
"BHMM people" are John and me. I don't think John wants to support pip 
anyway, so we need to do it. Since I don't know how this works yet, can 
you do that please Martin?

Am 31/07/15 um 13:28 schrieb Martin K. Scherer:

> I think 0.4.2 is not on pypi, since bhmm people are not releasing
> systematically everything but only the stuff individuals need (conda
> packages). This is very bad practice and should be avoided/fixed.
> 
> Please install bhmm with conda, then it will work.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/471#issuecomment-126659798.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I send in a PR, which pushes a source archive to pypi for every released 
version, but it has never been activated in the sense, one need to 
encrypt pypi credentials for the task. I will do this now in a way, 
nobody has to care about this again, because a tag push to github is 
sufficent to trigger a pypi release.

**Comment by franknoe** [comment]
Sorry, do I need to merge a PR? I may have missed it. There are 
currently three PR's which seem to be on different things. They also all 
failed in their tests (probably msmtools problems)

Am 31/07/15 um 14:34 schrieb Martin K. Scherer:

> I send in a PR, which pushes a source archive to pypi for every released
> version, but it has never been activated in the sense, one need to
> encrypt pypi credentials for the task. I will do this now in a way,
> nobody has to care about this again, because a tag push to github is
> sufficent to trigger a pypi release.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/471#issuecomment-126676344.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
This was already merged months ago.

**Comment by franknoe** [comment]
ok

Am 31/07/15 um 14:34 schrieb Martin K. Scherer:

> I send in a PR, which pushes a source archive to pypi for every released
> version, but it has never been activated in the sense, one need to
> encrypt pypi credentials for the task. I will do this now in a way,
> nobody has to care about this again, because a tag push to github is
> sufficent to trigger a pypi release.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/471#issuecomment-126676344.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by ppxasjsm** [comment]
Ok after also 'manually'=(condo install) installing msmtools, the development install worked fine.
