### ISSUE TITLE
cannot install latest devel version 

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#646]
With the current devel version (https://github.com/markovmodel/PyEMMA/commit/65282e810bc9642b487051ccaf6df80770a3a813) and with both python 2.7 and 3.5 (using miniconda and miniconda3, respectively)  python setup.py develop produces this when trying to install psutils:

```
Searching for psutil>=3.1.1
Reading https://pypi.python.org/simple/psutil/
Best match: psutil 3.3.0
Downloading https://pypi.python.org/packages/source/p/psutil/psutil-3.3.0.tar.gz#md5=0625db01ea46417308db94cc59362b65
Processing psutil-3.3.0.tar.gz
Writing /tmp/easy_install-IS2ZIY/psutil-3.3.0/setup.cfg
Running psutil-3.3.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-IS2ZIY/psutil-3.3.0/egg-dist-tmp-7RqitD
Traceback (most recent call last):
  File "setup.py", line 249, in <module>
    setup(**metadata)
  File "/home/mi/gph82/miniconda/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/mi/gph82/miniconda/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/mi/gph82/miniconda/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/command/develop.py", line 32, in run
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/command/develop.py", line 132, in install_for_development
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/command/easy_install.py", line 718, in process_distribution
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/pkg_resources/__init__.py", line 843, in resolve
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/pkg_resources/__init__.py", line 1088, in best_match
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/pkg_resources/__init__.py", line 1100, in obtain
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/command/easy_install.py", line 638, in easy_install
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/command/easy_install.py", line 668, in install_item
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/command/easy_install.py", line 851, in install_eggs
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/command/easy_install.py", line 1079, in build_and_install
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/command/easy_install.py", line 1065, in run_setup
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 240, in run_setup
  File "/home/mi/gph82/miniconda/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 193, in setup_context
  File "/home/mi/gph82/miniconda/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 152, in save_modules
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 126, in __exit__
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mi/gph82/miniconda/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/setuptools/sandbox.py", line 110, in dump
MemoryError
```

Any ideas?

**Comment by gph82** [comment]
After conversation with @marscher, circumvented installation of psutil at the moment of python setup.py develop by issuing conda install psutil just before. Leaving this here for future reference

**Comment by marscher** [comment]
Upstream bug report: https://bitbucket.org/pypa/setuptools/issues/448/develop-mode-in-anaconda-environment

**Comment by gph82** [comment]
After conversation with @franknoe , is this still needed? Do we use psutil?

**Comment by marscher** [comment]
psutil is used by kmeans to determine free memory from the operationg system

**Comment by marscher** [comment]
Should we leave this open until it is fixed upstream?

**Comment by marscher** [comment]
giampaolo/psutil/issues/699

**Comment by marscher** [comment]
the latest setuptools version raises the following error now. This suggests in my opinion, that the extension handling in psutils setup.py is somehow borked. I'm closing this now, because we can not handle it our selfs.

``` python
  File "/home/mi/marscher/miniconda/envs/testt/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/sandbox.py", line 46, in _execfile
  File "/tmp/easy_install-ccgdRg/psutil-3.3.0/setup.py", line 268, in <module>

  File "/tmp/easy_install-ccgdRg/psutil-3.3.0/setup.py", line 265, in main

  File "/home/mi/marscher/miniconda/envs/testt/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/mi/marscher/miniconda/envs/testt/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/mi/marscher/miniconda/envs/testt/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/mi/marscher/miniconda/envs/testt/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/bdist_egg.py", line 151, in run
  File "/home/mi/marscher/miniconda/envs/testt/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/home/mi/marscher/miniconda/envs/testt/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/mi/marscher/miniconda/envs/testt/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/egg_info.py", line 185, in run
  File "/home/mi/marscher/miniconda/envs/testt/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/egg_info.py", line 208, in find_sources
  File "/home/mi/marscher/miniconda/envs/testt/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/egg_info.py", line 292, in run
  File "/home/mi/marscher/miniconda/envs/testt/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/egg_info.py", line 321, in add_defaults
  File "/home/mi/marscher/miniconda/envs/testt/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/sdist.py", line 131, in add_defaults
  File "/home/mi/marscher/miniconda/envs/testt/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/home/mi/marscher/miniconda/envs/testt/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/home/mi/marscher/miniconda/envs/testt/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/build_ext.py", line 97, in finalize_options
  File "/home/mi/marscher/miniconda/envs/testt/lib/python2.7/distutils/command/build_ext.py", line 362, in check_extensions_list
    ("each element of 'ext_modules' option must be an "
setuptools.sandbox.UnpickleableException: DistutilsSetupError("each element of 'ext_modules' option must be an Extension instance or 2-tuple",
```

**Comment by franknoe** [comment]
pfff... can we get rid of the psutils dep? Maybe just copy the relevant 
part of psutils to ext? I think it's a small package.

Am 11/01/16 um 19:04 schrieb Martin K. Scherer:

> the latest setuptools version raises the following error now. This 
> suggests in my opinion, that the extension handling in psutils 
> setup.py is somehow borked. I'm closing this now, because we can not 
> handle it our selfs.
> 
>    File"/home/mi/marscher/miniconda/envs/testt/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/sandbox.py", line46,in  _execfile
>    File"/tmp/easy_install-ccgdRg/psutil-3.3.0/setup.py", line268,in  <module>
> 
>    File"/tmp/easy_install-ccgdRg/psutil-3.3.0/setup.py", line265,in  main
> 
>    File"/home/mi/marscher/miniconda/envs/testt/lib/python2.7/distutils/core.py", line151,in  setup
>      dist.run_commands()
>    File"/home/mi/marscher/miniconda/envs/testt/lib/python2.7/distutils/dist.py", line953,in  run_commands
>      self.run_command(cmd)
>    File"/home/mi/marscher/miniconda/envs/testt/lib/python2.7/distutils/dist.py", line972,in  run_command
>      cmd_obj.run()
>    File"/home/mi/marscher/miniconda/envs/testt/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/bdist_egg.py", line151,in  run
>    File"/home/mi/marscher/miniconda/envs/testt/lib/python2.7/distutils/cmd.py", line326,in  run_command
>      self.distribution.run_command(command)
>    File"/home/mi/marscher/miniconda/envs/testt/lib/python2.7/distutils/dist.py", line972,in  run_command
>      cmd_obj.run()
>    File"/home/mi/marscher/miniconda/envs/testt/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/egg_info.py", line185,in  run
>    File"/home/mi/marscher/miniconda/envs/testt/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/egg_info.py", line208,in  find_sources
>    File"/home/mi/marscher/miniconda/envs/testt/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/egg_info.py", line292,in  run
>    File"/home/mi/marscher/miniconda/envs/testt/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/egg_info.py", line321,in  add_defaults
>    File"/home/mi/marscher/miniconda/envs/testt/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/sdist.py", line131,in  add_defaults
>    File"/home/mi/marscher/miniconda/envs/testt/lib/python2.7/distutils/cmd.py", line312,in  get_finalized_command
>      cmd_obj.ensure_finalized()
>    File"/home/mi/marscher/miniconda/envs/testt/lib/python2.7/distutils/cmd.py", line109,in  ensure_finalized
>      self.finalize_options()
>    File"/home/mi/marscher/miniconda/envs/testt/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/build_ext.py", line97,in  finalize_options
>    File"/home/mi/marscher/miniconda/envs/testt/lib/python2.7/distutils/command/build_ext.py", line362,in  check_extensions_list
>      ("each element of 'ext_modules' option must be an "
> setuptools.sandbox.UnpickleableException: DistutilsSetupError("each element of 'ext_modules' option must be an Extension instance or 
> 2-tuple",
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/646#issuecomment-170636162.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by rmcgibbo** [comment]
FWIW, I just ran 

```
git clone git@github.com:markovmodel/PyEMMA.git
cd PyEMMA
pip install -e .
```

(i.e. `python setup.py install => pip install .`, `python setup.py develop => pip install -e .`, cc: https://mail.python.org/pipermail/distutils-sig/2015-November/027494.html)

and everything installed fine, including psutils.

**Comment by rmcgibbo** [comment]
Also, if you're looking for a better solution for developers/users that want to get the latest head of the devel branch for testing, but would prefer not to compile from source, John was working on https://github.com/omnia-md/conda-dev-recipes over the weekend. The idea is to have a repo with conda recipes that build the development HEAD of different projects, and all the recipes are triggered to automatically rebuild on a daily or twice daily schedule. So `conda install openmm-dev`, for example, will install the latest (modulo 12 or 24 hours) devel snapshot of OpenMM. So if that accomplishes your goals, you could add a recipe for `pyemma-dev` there.

**Comment by franknoe** [comment]
That's a good suggestion. How do you handle dependencies? Do you then 
also use the -dev versions for those?

Am 11/01/16 um 20:57 schrieb Robert T. McGibbon:

> Also, if you're looking for a better solution for developers/users 
> that want to get the latest head of the devel branch for testing, but 
> would prefer not to compile from source, John was working on 
> https://github.com/omnia-md/conda-dev-recipes over the weekend. The 
> idea is to have a repo with conda recipes that build the development 
> HEAD of different projects, and all the recipes are triggered to 
> automatically rebuild on a daily or twice daily schedule. So |conda 
> install openmm-dev|, for example, will install the latest (modulo 12 
> or 24 hours) devel snapshot of OpenMM. So if that accomplishes your 
> goals, you could add a recipe for |pyemma-dev| there.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/646#issuecomment-170671436.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by rmcgibbo** [comment]
I don't think we've really crossed that bridge -- it's up to you. I think you could either depend on `-dev` versions (if they exist) or on the regular versions.

The openmm-dev [recipe](https://github.com/omnia-md/conda-dev-recipes/blob/master/openmm-dev/meta.yaml) is the only one that currently exists there, and it doesn't have any dependencies that are fast-moving (FFWT3 is its only runtime dependency other than python, and I don't think they've made a release in ages).

Also, I don't want to promise too much. That infrastructure is still brand new (see https://github.com/omnia-md/conda-dev-recipes/issues/4), so it might require some tweaking and fiddling to get working for y'all.
