### ISSUE TITLE
[coor_refactor] fix feature_reader random access

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#663]
``` python
======================================================================
ERROR: test_feature_reader_random_access (__main__.TestRandomAccessStride)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pyemma/coordinates/tests/test_random_access_stride.py", line 172, in test_feature_reader_random_access
    out = source.get_output(stride=self.stride)
  File "/home/marscher/workspace/pyemma/pyemma/coordinates/data/iterable.py", line 134, in get_output
    for itraj, chunk in it:
  File "/home/marscher/workspace/pyemma/pyemma/coordinates/data/datasource.py", line 297, in next
    X = self.next_chunk()
  File "/home/marscher/workspace/pyemma/pyemma/coordinates/data/feature_reader.py", line 201, in next_chunk
    chunk = next(self._mditer)
  File "/home/marscher/workspace/pyemma/pyemma/coordinates/util/patches.py", line 140, in next
    return load(self._filename, stride=self._stride, **self._kwargs)[self._skip:]
  File "/home/marscher/sources/mdtraj_/mdtraj/core/trajectory.py", line 420, in load
    value = loader(filename, **kwargs)
  File "mdtraj/formats/xtc/xtc.pyx", line 133, in xtc.load_xtc (mdtraj/formats/xtc/xtc.c:2228)
    with XTCTrajectoryFile(filename, 'r') as f:
  File "mdtraj/formats/xtc/xtc.pyx", line 140, in xtc.load_xtc (mdtraj/formats/xtc/xtc.c:2183)
    return f.read_as_traj(topology, n_frames=n_frames, stride=stride,
  File "mdtraj/formats/xtc/xtc.pyx", line 303, in xtc.XTCTrajectoryFile.read_as_traj (mdtraj/formats/xtc/xtc.c:3772)
    xyz, time, step, box = self.read(n_frames=n_frames, stride=stride, atom_indices=atom_indices)
  File "mdtraj/formats/xtc/xtc.pyx", line 383, in xtc.XTCTrajectoryFile.read (mdtraj/formats/xtc/xtc.c:5080)
    all_xyz = np.concatenate(all_xyz)[::stride]
IndexError: invalid slice
```

**Comment by marscher** [comment]
if one redirects to the proper ra_inds code branch, one gets the following error message:

``` python

Traceback (most recent call last):
  File "pyemma/coordinates/tests/test_random_access_stride.py", line 172, in test_feature_reader_random_access
    out = source.get_output(stride=self.stride)
  File "/home/marscher/workspace/pyemma/pyemma/coordinates/data/iterable.py", line 135, in get_output
    for itraj, chunk in it:
  File "/home/marscher/workspace/pyemma/pyemma/coordinates/data/datasource.py", line 297, in next
    X = self.next_chunk()
  File "/home/marscher/workspace/pyemma/pyemma/coordinates/data/feature_reader.py", line 201, in next_chunk
    chunk = next(self._mditer)
  File "/home/marscher/workspace/pyemma/pyemma/coordinates/util/patches.py", line 147, in next
    return next(self._ra_it)
  File "/home/marscher/workspace/pyemma/pyemma/coordinates/util/patches.py", line 176, in _random_access_generator
    grouped_stride = list(map(itemgetter(1), g))
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
