### ISSUE TITLE
error when running  pyemma.thermo.estimate_umbrella_sampling with the estimator='wham' option

### ISSUE THREAD

**Issue by cclementi** [markovmodel/PyEMMA#826]
Hi, I am running wham using the function: pyemma.thermo.estimate_umbrella_sampling and, while it works fine with the estimator='tram' option, it gives me a weird error if I use the estimator='wham' option, with exactly the same data.
This is what I am running:

``` python
wham = pyemma.thermo.estimate_umbrella_sampling(
    us_trajs, us_dtrajs, us_centers, us_force_constants, md_trajs = md_trajs, md_dtrajs = md_dtrajs, 
    maxiter=1500000, maxerr=5e-14, save_convergence_info=50, estimator='wham')
```

And this is the error I get:

``` python
Traceback (most recent call last):
  File "../WHAM_fisDNA_all.py", line 126, in <module>
    us_trajs, us_dtrajs, us_centers, us_force_constants, md_trajs = md_trajs, md_dtrajs = md_dtrajs, estimator='wham')
  File "/home/mi/cclementi/anaconda2/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/thermo/api.py", line 158, in estimate_umbrella_sampling
    save_convergence_info=save_convergence_info, dt_traj=dt_traj)
  File "/home/mi/cclementi/anaconda2/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/thermo/api.py", line 773, in wham
    return wham_estimator.estimate((ttrajs, dtrajs))
  File "/home/mi/cclementi/anaconda2/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/_base/estimator.py", line 348, in estimate
    self._model = self._estimate(X)
  File "/home/mi/cclementi/anaconda2/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/thermo/estimators/WHAM_estimator.py", line 157, in _estimate
    self._progress_force_finish(stage='WHAM')
  File "/home/mi/cclementi/anaconda2/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/_base/progress/reporter.py", line 206, in _progress_force_finish
    _show_progressbar(pg, description=self._prog_rep_descriptions[stage])
  File "/home/mi/cclementi/anaconda2/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/_base/progress/bar/gui.py", line 176, in show_progressbar
    sys.stdout.write("\r" + str(bar))
  File "/home/mi/cclementi/anaconda2/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/_base/progress/bar/_impl.py", line 346, in __str__
    template.format(bar=''), self.max_width or None)
```

If I understand the error message, it's complaining about the progress bar? 

Thanks!

**Comment by cwehmeyer** [comment]
You are correct, this is caused by the progress bar. Unfortunately, I cannot reproduce this exception with the pyemma-2.2 version from the omnia channel (which, I presume, you are using).

You could switch to the development version. The progress bar implementation has been changed recently and I would like to know if this exception would still appear.

**Comment by cclementi** [comment]
Yes, I am using the pyemma-2.2 version from the omnia channel.
I am running at FU on shark, I will give you access to my dir and send you an email with the details on what I am running. In the meantime I can also try the development version.

Thanks!

**Comment by cwehmeyer** [comment]
OK, I can reproduce this exception with pyemma-2.2 on shark. Switching to the development version fixes the issue.
