### ISSUE TITLE
segfault in KmeansClustering

### ISSUE THREAD

**Issue by jchodera** [markovmodel/PyEMMA#838]
Has anyone run into segfaults in `KmeansClustering` before?

```
loading reference topology...
Initializing featurizer...
Obtaining file info: 100% (558/558) [##############################] eta 00:01 -There are 696874 frames total in 558 trajectories.
Clustering...
22-06-16 23:19:41 pyemma.coordinates.clustering.kmeans.KmeansClustering[0] INFO     number of threads obtained from env variable 'OMP_NUM_THREADS'=16
initialize kmeans++ centers:   0% (   1/2787) [                    ] eta --:-- \/var/spool/torque/mom_priv/jobs/7516948.hal-sched1.local.SC: line 42: 48885 Segmentation fault      (core dumped) python cluster.py
```

Here is my script:

``` python
#!/usr/bin/env python

import pyemma
import numpy as np
import mdtraj
import time
import os

# Source directory
source_directory = '/cbio/jclab/projects/fah/fah-data/munged3/no-solvent/11406' # CK2
#source_directory = '11406' # CK2

################################################################################
# Load reference topology
################################################################################

print ('loading reference topology...')
reference_pdb_filename = 'protein.pdb'
reference_trajectory = os.path.join(source_directory, 'run0-clone0.h5')
traj = mdtraj.load(reference_trajectory)
traj[0].save_pdb(reference_pdb_filename)

################################################################################
# Initialize featurizer
################################################################################

print('Initializing featurizer...')
import pyemma.coordinates
featurizer = pyemma.coordinates.featurizer(reference_pdb_filename)
#featurizer.add_all() # all atoms
featurizer.add_selection( featurizer.select_Heavy() ) # add heavy atoms

################################################################################
# Define coordinates source
################################################################################

import pyemma.coordinates
from glob import glob
trajectory_filenames = glob(os.path.join(source_directory, 'run*-clone*.h5'))
coordinates_source = pyemma.coordinates.source(trajectory_filenames, features=featurizer)
print("There are %d frames total in %d trajectories." % (coordinates_source.n_frames_total(), coordinates_source.number_of_trajectories()))

################################################################################
# Cluster
################################################################################

print('Clustering...')
generator_ratio = 250
nframes = coordinates_source.n_frames_total()
nstates = int(nframes / generator_ratio)
stride = 1
metric = 'minRMSD'
initial_time = time.time()
#clustering = pyemma.coordinates.cluster_uniform_time(data=coordinates_source, k=nstates, stride=stride, metric=metric)
clustering = pyemma.coordinates.cluster_kmeans(data=coordinates_source, k=nstates, stride=stride, metric=metric, max_iter=10)
final_time = time.time()
elapsed_time = final_time - initial_time
print('Elapsed time %.3f s' % elapsed_time)

# Save cluster centers
np.save('clustercenters', clustering.clustercenters)

# Save discrete trajectories.
dtrajs = clustering.dtrajs
dtrajs_dir = 'dtrajs'
clustering.save_dtrajs(output_dir=dtrajs_dir, output_format='npy', extension='.npy')

################################################################################
# Make timescale plots
################################################################################

import matplotlib as mpl
mpl.use('Agg') # Don't use display
import matplotlib.pyplot as plt

from pyemma import msm
from pyemma import plots

lags = [1,2,5,10,20,50]
its = msm.its(dtrajs, lags=lags, errors='bayes')
plots.plot_implied_timescales(its)

plt.savefig('plot.pdf')
```

The dataset is rather large (63G), but I can give people access to it if needed, or try to prepare a smaller test dataset.

**Comment by marscher** [comment]
The data-set is really massive for a feasible run of kmeans, since we 
first accumulate the data to run kmeans iterations efficiently. How much 
RAM does this machine have?

Actually I recommend using mini-batch-kmeans.

However I'm curious what exactly is seg-faulting here, since the case of 
not enough memory is handled accordingly.

The output states, that the applications memory core had been dumped. 
Can you quickly load this into GDB and obtain a stacktrace?

```
gdb python core.dump
(gdb) bt

```

**Comment by marscher** [comment]
I can reproduce the crash with a large fake data-set. The backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007fefd9c9040e in minRMSD_distance (a=0x7fe7d9c8c210, 
b=0x7fe7d9c8c010, n=<optimized out>, buffer_a=<optimized out>, 
buffer_b=0x1d171c0, trace_a_precalc=0x8)
     at pyemma/coordinates/clustering/src/clustering.c:66
warning: Source file is more recent than executable.
66              // only copy b, since a has been pre-centered,
(gdb) bt
#0  0x00007fefd9c9040e in minRMSD_distance (a=0x7fe7d9c8c210, 
b=0x7fe7d9c8c010, n=<optimized out>, buffer_a=<optimized out>, 
buffer_b=0x1d171c0,
     trace_a_precalc=0x8) at 
pyemma/coordinates/clustering/src/clustering.c:66
#1  0x00007fefd9c8f4c1 in initCentersKMpp (self=<optimized out>, 
args=<optimized out>) at pyemma/coordinates/clustering/src/kmeans.c:410
```

Actually the pointer to the pre-calculated trace is set to NULL in the 
source (kmeans.c:410), but within the execution the actual value is 0x8...

**Comment by marscher** [comment]
it seems NULL is not set 0x0. When defining it explicitly, there is no crash any more.

**Comment by jchodera** [comment]
Awesome, thanks!

**Comment by marscher** [comment]
Thank you for testing.
