### ISSUE TITLE
[xtc lagged iterators] error for short trajectories?

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#880]
I'm observing this new behavior in the last devel version, where the iterators are not able to skip too short trajectories. That was normally possible. Anybody has a clue of what happened? 

``` python
print(pyemma.__version__)
src = pyemma.coordinates.source(xtc_list[:2], top=pdbfile)
itr = src.iterator(lag=tau_val, return_trajindex=False)
print("trajctory lengths", src.trajectory_lengths())
print("iterator lag", tau_val)
#2.2.2+22.g49e4a3d
# trajctory lengths [ 201 1401]
# iterator lag 500
```

Then:

``` python
for X, Y in itr:
    print(X.shape)

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-66-5de043d181ea> in <module>()
----> 1 for X, Y in itr:
      2     print(X.shape)

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/data/_base/iterable.py in __next__(self)
    356 
    357     def __next__(self):
--> 358         return self.next()
    359 
    360     def next(self):

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/data/_base/iterable.py in next(self)
    360     def next(self):
    361         itraj, data = self._it.next()
--> 362         itraj_lag, data_lagged = self._it_lagged.next()
    363 
    364         while itraj < itraj_lag:

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/data/_base/datasource.py in next(self)
    642 
    643     def next(self):
--> 644         X = self._it_next()
    645         while X is not None and (
    646                 (not self.return_traj_index and len(X) == 0) or (self.return_traj_index and len(X[1]) == 0)

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/data/_base/datasource.py in _it_next(self)
    622         self.state.pos = self.state.pos_adv
    623         try:
--> 624             X = self._use_cols(self._next_chunk())
    625         except StopIteration:
    626             self._last_chunk_in_traj = True

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/data/feature_reader.py in _next_chunk(self)
    338         :return: a feature mapped vector X, or (X, Y) if lag > 0
    339         """
--> 340         chunk = next(self._mditer)
    341         shape = chunk.xyz.shape
    342 

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/util/patches.py in __next__(self)
    161 
    162     def __next__(self):
--> 163         return self.next()
    164 
    165     def next(self):

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/util/patches.py in next(self)
    170         # (we want to do this here, since we want to be able to re-set self.skip)
    171         if not self._seeked:
--> 172             self._f.seek(self.skip)
    173             self._seeked = True
    174 

mdtraj/formats/xtc/xtc.pyx in xtc.XTCTrajectoryFile.seek (mdtraj/formats/xtc/xtc.c:8691)()

IndexError: index 500 is out of bounds for axis 0 with size 201
```

**Comment by gph82** [comment]
And, BTW, same thing would happen using the tica function (I used the iterator directly to make it clearer). Here's what happens:

``` python
tica = pyemma.coordinates.tica(src, lag=tau_val)

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-69-cc103371ecbd> in <module>()
----> 1 tica = pyemma.coordinates.tica(src, lag=tau_val)

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/api.py in tica(data, lag, dim, var_cutoff, kinetic_map, stride, force_eigenvalues_le_one, mean, remove_mean)
   1151     res = TICA(lag, dim=dim, var_cutoff=var_cutoff, kinetic_map=kinetic_map,
   1152                mean=mean, remove_mean=remove_mean)
-> 1153     return _param_stage(data, res, stride=stride)
   1154 
   1155 

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/api.py in _param_stage(previous_stage, this_stage, stride, chunk_size)
    834     # parametrize transformer
    835     this_stage.data_producer = input_stage
--> 836     this_stage.estimate(X=input_stage, stride=stride)
    837     return this_stage
    838 

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/transform/tica.py in estimate(self, X, **kwargs)
    255         the independent components.
    256         """
--> 257         return super(TICA, self).estimate(X, **kwargs)
    258 
    259     def _estimate(self, iterable, **kw):

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/transform/transformer.py in estimate(self, X, **kwargs)
    188         # run estimation
    189         try:
--> 190             super(StreamingTransformer, self).estimate(X, **kwargs)
    191         except NotConvergedWarning as ncw:
    192             self._logger.info(

/home/mi/gph82/programs/PyEmma/pyemma/_base/estimator.py in estimate(self, X, **params)
    346         if params:
    347             self.set_params(**params)
--> 348         self._model = self._estimate(X)
    349         self._estimated = True
    350         return self

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/transform/tica.py in _estimate(self, iterable, **kw)
    285             self._progress_register(it._n_chunks, "calculate mean+cov", 0)
    286             self._init_covar(partial_fit, it._n_chunks)
--> 287             for X, Y in it:
    288                 self._covar.add(X, Y)
    289                 # counting chunks and log of eta

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/data/_base/iterable.py in __next__(self)
    356 
    357     def __next__(self):
--> 358         return self.next()
    359 
    360     def next(self):

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/data/_base/iterable.py in next(self)
    360     def next(self):
    361         itraj, data = self._it.next()
--> 362         itraj_lag, data_lagged = self._it_lagged.next()
    363 
    364         while itraj < itraj_lag:

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/data/_base/datasource.py in next(self)
    642 
    643     def next(self):
--> 644         X = self._it_next()
    645         while X is not None and (
    646                 (not self.return_traj_index and len(X) == 0) or (self.return_traj_index and len(X[1]) == 0)

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/data/_base/datasource.py in _it_next(self)
    622         self.state.pos = self.state.pos_adv
    623         try:
--> 624             X = self._use_cols(self._next_chunk())
    625         except StopIteration:
    626             self._last_chunk_in_traj = True

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/data/feature_reader.py in _next_chunk(self)
    338         :return: a feature mapped vector X, or (X, Y) if lag > 0
    339         """
--> 340         chunk = next(self._mditer)
    341         shape = chunk.xyz.shape
    342 

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/util/patches.py in __next__(self)
    161 
    162     def __next__(self):
--> 163         return self.next()
    164 
    165     def next(self):

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/util/patches.py in next(self)
    170         # (we want to do this here, since we want to be able to re-set self.skip)
    171         if not self._seeked:
--> 172             self._f.seek(self.skip)
    173             self._seeked = True
    174 

mdtraj/formats/xtc/xtc.pyx in xtc.XTCTrajectoryFile.seek (mdtraj/formats/xtc/xtc.c:8691)()

IndexError: index 500 is out of bounds for axis 0 with size 201
```

**Comment by marscher** [comment]
Hey, 
thanks for the report! We moved the initial seeking for the lag time from the constructor of mdtraj iterators to the next method (which is invoked for every chunk), because we wanted to be able to reset the skip parameter for an existing iterator. However we haven't had too short trajectories in mind.

A simple fix would surround the seek call with try catch IndexError and raise a StopIteration to indicate a too short trajectory.

**Comment by gph82** [comment]
We we're writing at the same time. Turns out this only happens with XTCs, and I can confirm it's happening with commits as old as January! (thanks, git bisect) 

So I doubt any recent changes made this, after all.

**Comment by gph82** [comment]
``` python
from pyemma.coordinates import source
import pyemma
tau = 10
src = source(['/home/mi/gph82/short.xtc', '/home/mi/gph82/long.xtc'], top='/home/mi/gph82/cl.pdb')
print("traj lengths", src.trajectory_lengths())
print("tau ", tau)
print("pyemma version",pyemma.__version__)
for x in src.iterator(lag=tau):
    x
```

Output

``` python
traj lengths [ 8 16]
tau  10
pyemma version 2.0.2-169-g93bd8eb
Traceback (most recent call last):
  File "/home/mi/gph82/test.py", line 8, in <module>
    for x in src.iterator(lag=tau):
  File "/home/mi/gph82/programs/PyEmma/pyemma/coordinates/data/iterable.py", line 81, in iterator
    it_lagged = self._create_iterator(skip=lag, chunk=chunk, stride=stride, return_trajindex=True)
  File "/home/mi/gph82/programs/PyEmma/pyemma/coordinates/data/feature_reader.py", line 150, in _create_iterator
    return_trajindex=return_trajindex)
  File "/home/mi/gph82/programs/PyEmma/pyemma/coordinates/data/feature_reader.py", line 188, in __init__
    self._create_mditer()
  File "/home/mi/gph82/programs/PyEmma/pyemma/coordinates/data/feature_reader.py", line 243, in _create_mditer
    self._data_source.trajfiles[self._itraj], skip=self.skip, stride=self.stride
  File "/home/mi/gph82/programs/PyEmma/pyemma/coordinates/data/feature_reader.py", line 248, in _create_patched_iter
    skip=skip, stride=stride, atom_indices=atom_indices)
  File "/home/mi/gph82/programs/PyEmma/pyemma/coordinates/util/patches.py", line 116, in __init__
    self._f.seek(self._skip)
  File "mdtraj/formats/xtc/xtc.pyx", line 595, in xtc.XTCTrajectoryFile.seek (mdtraj/formats/xtc/xtc.c:8691)
IndexError: index 10 is out of bounds for axis 0 with size 8
```

**Comment by marscher** [comment]
mhm, I guess you're not using mdtraj-1.7.2?

**Comment by marscher** [comment]
I think the proposed PR should fix this.

**Comment by gph82** [comment]
I just fetched your branch and my example is working now. So we should be okay

**Comment by marscher** [comment]
thanks for testing!

**Comment by gph82** [comment]
Sorry to bring bad news, @marscher, but now now this happens:

``` python
src = pyemma.coordinates.source(xtc_list[:2], top=pdbfile)
print("tau val", src.trajectory_lengths())
print("tau_val", tau_val)
pyemma.coordinates.tica(src, tau_val)
```

output:

``` python
tau val [ 201 1401]
tau_val 500

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-21-0b246165b51d> in <module>()
      2 print("tau val", src.trajectory_lengths())
      3 print("tau_val", tau_val)
----> 4 pyemma.coordinates.tica(src, tau_val)

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/api.py in tica(data, lag, dim, var_cutoff, kinetic_map, stride, force_eigenvalues_le_one, mean, remove_mean)
   1151     res = TICA(lag, dim=dim, var_cutoff=var_cutoff, kinetic_map=kinetic_map,
   1152                mean=mean, remove_mean=remove_mean)
-> 1153     return _param_stage(data, res, stride=stride)
   1154 
   1155 

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/api.py in _param_stage(previous_stage, this_stage, stride, chunk_size)
    834     # parametrize transformer
    835     this_stage.data_producer = input_stage
--> 836     this_stage.estimate(X=input_stage, stride=stride)
    837     return this_stage
    838 

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/transform/tica.py in estimate(self, X, **kwargs)
    255         the independent components.
    256         """
--> 257         return super(TICA, self).estimate(X, **kwargs)
    258 
    259     def _estimate(self, iterable, **kw):

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/transform/transformer.py in estimate(self, X, **kwargs)
    188         # run estimation
    189         try:
--> 190             super(StreamingTransformer, self).estimate(X, **kwargs)
    191         except NotConvergedWarning as ncw:
    192             self._logger.info(

/home/mi/gph82/programs/PyEmma/pyemma/_base/estimator.py in estimate(self, X, **params)
    346         if params:
    347             self.set_params(**params)
--> 348         self._model = self._estimate(X)
    349         self._estimated = True
    350         return self

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/transform/tica.py in _estimate(self, iterable, **kw)
    290                 self._progress_update(1, stage=0)
    291 
--> 292         self._model.update_model_params(mean=self._covar.mean_X(),
    293                                         cov=self._covar.cov_XX(),
    294                                         cov_tau=self._covar.cov_XY())

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/estimators/covar/running_moments.py in mean_X(self)
    265     def mean_X(self):
    266         if self.compute_XX:
--> 267             return self.storage_XX.moments.mean_x
    268         elif self.compute_XY:
    269             return self.storage_XY.moments.mean_y

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/estimators/covar/running_moments.py in moments(self)
    150             self.storage[-1].combine(M, mean_free=self.remove_mean)
    151         # print 'return first element'
--> 152         return self.storage[0]
    153 
    154 

IndexError: list index out of range
```

**Comment by marscher** [comment]
Am 28.07.2016 um 16:23 schrieb Guillermo Pérez-Hernández:

> Sorry to bring bad news, @marscher https://github.com/marscher, but now now this happens:
> OK. I guess I know whats going on now...

**Comment by marscher** [comment]
I guess this is a bug in covartools, since it requires at least two storage instances to operate, but this test case will only produce one valid chunk.
This won't hurt in practice as you will most likely have more than one chunk/file

**Comment by gph82** [comment]
sorry but it's failing also with this...

``` python
src = pyemma.coordinates.source(xtc_list[:5], top=pdbfile,  chunksize=5)
print("tau val", src.trajectory_lengths())
print("tau_val", tau_val)
pyemma.coordinates.tica(src, tau_val,)
tau val [ 201 1401  401  601 1801]
tau_val 500
```

**Comment by gph82** [comment]
Hope this helps: When only one file is used, no error appears:

``` python
feat = pyemma.coordinates.featurizer(pdbfile)
feat.add_selection(feat.topology.select("name CA"))
src = pyemma.coordinates.source(xtc_list[1], feat,  chunksize=5)
print("tau val", src.trajectory_lengths())
print("tau_val", tau_val)
pyemma.coordinates.tica(src, tau_val,)
```

works like a charm. Note that I've added the feature "CA" s.t. the tica diagonalization didn't take ages

**Comment by marscher** [comment]
the problem is, that the iterator now stops upon the first too short trajectory, whereas it should continue with the next file
