### ISSUE TITLE
Trajectory info cache sometimes tries to use /

### ISSUE THREAD

**Issue by jchodera** [markovmodel/PyEMMA#905]
On travis-ci, we are noticing that the trajectory info cache sometimes tries to write to `/` with the conda version of `pyemma 2.2.3` or the current git head:

From [this log](https://travis-ci.org/choderalab/msm-pipeline/jobs/153712453#L680-L714):

```
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/_test/bin/msm-pipeline", line 9, in <module>
    load_entry_point('msmpipeline==0.0.1', 'console_scripts', 'msm-pipeline')()
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/msmpipeline-0.0.1-py2.7.egg/msmpipeline/msmpipeline.py", line 188, in main
    run_pipeline(fnames, project_name = project_name, n_clusters = n_clusters)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/msmpipeline-0.0.1-py2.7.egg/msmpipeline/msmpipeline.py", line 69, in run_pipeline
    source = pyemma.coordinates.source(fnames, features = feat)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/pyEMMA-2.2.3-py2.7-linux-x86_64.egg/pyemma/coordinates/api.py", line 339, in source
    reader = create_file_reader(inp, top, features, chunk_size=chunk_size if chunk_size is not None else 100, **kw)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/pyEMMA-2.2.3-py2.7-linux-x86_64.egg/pyemma/coordinates/data/util/reader_utils.py", line 101, in create_file_reader
    chunksize=chunk_size)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/pyEMMA-2.2.3-py2.7-linux-x86_64.egg/pyemma/coordinates/data/feature_reader.py", line 92, in __init__
    self.filenames = trajectories
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/pyEMMA-2.2.3-py2.7-linux-x86_64.egg/pyemma/coordinates/data/_base/datasource.py", line 115, in filenames
    info = TrajectoryInfoCache.instance()[filename, self]
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/pyEMMA-2.2.3-py2.7-linux-x86_64.egg/pyemma/coordinates/data/util/traj_info_cache.py", line 199, in __getitem__
    self.__setitem__(info)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/pyEMMA-2.2.3-py2.7-linux-x86_64.egg/pyemma/coordinates/data/util/traj_info_cache.py", line 240, in __setitem__
    self._database.set(traj_info)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/pyEMMA-2.2.3-py2.7-linux-x86_64.egg/pyemma/coordinates/data/util/traj_info_backends.py", line 195, in set
    self._database_from_key(traj_info.hash_value)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/pyEMMA-2.2.3-py2.7-linux-x86_64.egg/pyemma/coordinates/data/util/traj_info_backends.py", line 250, in _database_from_key
    mkdir_p(directory)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/pyEMMA-2.2.3-py2.7-linux-x86_64.egg/pyemma/util/files.py", line 35, in mkdir_p
    os.makedirs(path)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/traj_info_usage'
```

[This comment](https://github.com/markovmodel/PyEMMA/blob/49e4a3dd68bfec6bf08cd14ed06efc4661e2d59a/pyemma/coordinates/data/util/traj_info_backends.py#L235-L236) suggests that `pyemma` will try to write the cache next to the source files by default, but doesn't explain how to prevent this from happening.  We're also not sure why the path is ending up as `/` on travis.

My two cents: I don't think that just writing files next to any specified trajectory source is a good idea. All other *nix tools I am familiar with write to a dot-prefixed directory in `$HOME` or the current directory unless otherwise specified with an environment variable or argument. It would be much more *nix-friendly to adopt this behavior as well, especially since multiple users might be trying to analyze read-only datasets stored in non-writeable places.

Tagging @maxentile.

**Comment by jchodera** [comment]
This seems like a duplicate of #882 (which was closed)

**Comment by marscher** [comment]
Do you invoke your script via nose/pytest or bash?

**Comment by marscher** [comment]
A comment to your two cents. We do not write the database file next to your trajectory files, but next to the main database, which is stored in exactly the place you have described (dot folder in $HOME). However Frank didn't want to have this by default (eg. it is not written until the user requests it).

Actually the LRU cache should not even be used, if there is only a "in-memory" database in your case. I will look into this again.

**Comment by jchodera** [comment]
Sorry for not being able to respond earlier! Thanks for the clarifications and bugfix here!
