### ISSUE TITLE
Some samples of BayesianMSM are not reversible

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#937]
This happens often ... (unfortunately I dont have the statistics, since I restart the jobs on Travis then, but it happens almost for every pull request).

```
======================================================================

FAIL: test_transition_matrix_samples (pyemma.msm.tests.test_bayesian_msm.TestBMSM)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/pyEMMA-2.2.4+3.g03b5bc5-py3.4-linux-x86_64.egg/pyemma/msm/tests/test_bayesian_msm.py", line 83, in test_transition_matrix_samples

    self._transition_matrix_samples(self.bmsm_revpi)

  File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/pyEMMA-2.2.4+3.g03b5bc5-py3.4-linux-x86_64.egg/pyemma/msm/tests/test_bayesian_msm.py", line 93, in _transition_matrix_samples

    assert msmana.is_reversible(P)

AssertionError
```

**Comment by marscher** [comment]
I only observed this on Travis and very rarely on Appveyor, but never locally (where I dont use MKL, which affects the eigen solver). Since the msmtools function is_reversible uses pi for the test, it could be that this caused by a not converged eigenvector. I'll add a PR on devel to obtain more info in the case this test fails.

**Comment by marscher** [comment]
does not happen any more.
